"""Authoritative Muraja ``PhonemeVocabulary`` snapshot — the parity source of truth.

Loads ``fixtures/muraja_phoneme_vocabulary.json``, an exported snapshot of Muraja's
on-device ``PhonemeVocabulary.swift`` (``sysofwan/Muraja``), which is the 43-class
Muaalem phoneme head as the iOS app decodes it. The snapshot is generated by parsing
the Swift source directly (see the fixture's ``_source`` block for repo/blob/commit),
so it is independent of this repo's own ``tadabur.phoneme_vocab`` constant.

``test_phoneme_vocab.py`` asserts *both* Tadabur's ``PHONEME_CHAR_TO_ID`` *and* the
live ``obadx/muaalem-model-v3_2`` ``vocab.json`` equal this snapshot exactly. Drift in
either direction fails loudly instead of silently corrupting decoded labels — the two
sources can no longer agree with each other while both having drifted from Muraja.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

_FIXTURE_PATH = Path(__file__).parent / "fixtures" / "muraja_phoneme_vocabulary.json"


@dataclass(frozen=True)
class MurajaPhonemeSnapshot:
    """Muraja's phoneme vocabulary as codified on-device.

    ``char_to_id`` covers only the emittable phonemes; the CTC blank (``blank_id``)
    has no character in Muraja's ``id2phoneme`` and is excluded here by design.
    """

    blank_id: int
    vocab_size: int
    char_to_id: dict[str, int]


def load_muraja_phoneme_snapshot() -> MurajaPhonemeSnapshot:
    """Load and validate the committed Muraja phoneme-vocabulary snapshot."""
    data = json.loads(_FIXTURE_PATH.read_text(encoding="utf-8"))
    blank_id = data["blank_id"]
    vocab_size = data["vocab_size"]

    char_to_id = {char: int(idx) for idx, char in data["id_to_phoneme"].items()}
    if len(char_to_id) != len(data["id_to_phoneme"]):
        raise ValueError(
            f"{_FIXTURE_PATH.name} has duplicate phoneme characters — the snapshot "
            "is not a bijection and cannot be a parity reference."
        )
    # The blank owns id 0 and no character; the emittable phonemes fill 1..vocab_size-1.
    if set(char_to_id.values()) != set(range(1, vocab_size)):
        raise ValueError(
            f"{_FIXTURE_PATH.name} phoneme ids {sorted(char_to_id.values())} are not "
            f"the contiguous range 1..{vocab_size - 1} around blank id {blank_id}."
        )
    if blank_id != 0:
        raise ValueError(
            f"{_FIXTURE_PATH.name} blank_id is {blank_id}; the CTC blank must be 0."
        )

    return MurajaPhonemeSnapshot(
        blank_id=blank_id, vocab_size=vocab_size, char_to_id=char_to_id
    )
